jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: lua-dui
          version: "Neovim >= 0.8.0"
          demojify: true
          treesitter: true

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore(ci): auto-generate vimdoc"
          commit_user_name: "kokaito-git[bot]"
          commit_user_email: "kokaito-git@users.noreply.github.com"
          commit_author: "kokaito-git <kokaito-git@users.noreply.github.com>"
